"""Regenerates the extracted Streamlit code in backtest_engine/legacy/.

Usage (from the engine/ folder):
    python tools/extract_legacy.py            # both pages
    python tools/extract_legacy.py multi      # 1_Multi_Backtest.py -> multi_backtest.py
    python tools/extract_legacy.py alloc      # 2_Allocations.py    -> allocations.py

Only definitions are kept (see legacy_ast.py). `import streamlit as st` is
replaced by the headless shim, so the calculation code is identical to the
Streamlit version.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENGINE_ROOT = HERE.parent
STREAMLIT_DIR = ENGINE_ROOT.parent / "Streamlit Momentum Backtester"
LEGACY_DIR = ENGINE_ROOT / "backtest_engine" / "legacy"
PAGES = {
    "multi": (STREAMLIT_DIR / "1_Multi_Backtest.py", LEGACY_DIR / "multi_backtest.py"),
    "alloc": (STREAMLIT_DIR / "2_Allocations.py", LEGACY_DIR / "allocations.py"),
}

sys.path.insert(0, str(HERE))
from legacy_ast import filter_definitions  # noqa: E402


def extract(source_path: Path, target: Path) -> None:
    src = source_path.read_text(encoding="utf-8")
    digest = hashlib.sha256(src.encode("utf-8")).hexdigest()[:16]
    header = (
        "# fmt: off\n"
        "# flake8: noqa\n"
        f"# AUTO-GENERATED by engine/tools/extract_legacy.py from {source_path.name} (sha256 {digest}).\n"
        "# Do not edit by hand: change the Streamlit source and regenerate.\n"
        "from backtest_engine.st_shim import st\n\n"
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(header + filter_definitions(src), encoding="utf-8")
    print(f"Wrote {target} from {source_path} ({digest})")


def main() -> None:
    names = sys.argv[1:] or list(PAGES)
    for name in names:
        extract(*PAGES[name])


if __name__ == "__main__":
    main()
